CREATE TABLE Calcs
(
    `key` VARCHAR(255),
    `num0` DOUBLE ,
    `num1` DOUBLE ,
    `num2` DOUBLE ,
    `num3` DOUBLE ,
    `num4` DOUBLE ,
    `str0` VARCHAR(255),
    `str1` VARCHAR(255),
    `str2` VARCHAR(255),
    `str3` VARCHAR(255),
    `int0` INTEGER,
    `int1` INTEGER,
    `int2` INTEGER,
    `int3` INTEGER,
    `bool0` INTEGER,
    `bool1` INTEGER,
    `bool2` INTEGER,
    `bool3` INTEGER,
    `date0` DATE,
    `date1` DATE,
    `date2` DATE,
    `date3` DATE,
    `time0` TIMESTAMP,
    `time1` TIME,
    `datetime0` TIMESTAMP,
    `datetime1` VARCHAR(255),
    `zzz` VARCHAR(255)
) distribute by hash(`key`);